// UI strings. English is the fallback. Have a native speaker review hi/pa before launch.
export const NUMS=[["112","main"],["100",""],["101",""],["102",""]];
export const NAMES={en:["Emergency","Police","Fire","Health"],hi:["आपातकाल","पुलिस","अग्निशमन","स्वास्थ्य"],pa:["ਐਮਰਜੈਂਸੀ","ਪੁਲਿਸ","ਅੱਗ ਬੁਝਾਊ","ਸਿਹਤ"]};
export const T={
en:{title:"Tell us what is happening",sub:"Say where you are and what help you need. A rescue coordinator sees it straight away.",ph:"For example: the building next to the market has collapsed and two people are trapped.",loc:"Add my location",locDone:"Location added",addr:"Street, area or landmark (optional)",send:"Send for help",call:"If someone's life is in danger, call",first:"first.",mine:"Your reports",alert:"Alert for your area",alertBody:"Heavy rain and flooding are expected in your district tonight. Keep valuables upstairs and stay off low roads.",src:"Sample alert. Issued by the district control room, 9:05 am.",helplines:"Emergency numbers",safety:"What to do during a flood",tips:["Move to higher ground early","Switch off electricity at the main switch","Do not walk or drive through flood water"]},
hi:{title:"बताइए क्या हो रहा है",sub:"आप कहाँ हैं और आपको क्या मदद चाहिए, यह लिखें। बचाव समन्वयक इसे तुरंत देखता है।",ph:"जैसे: बाज़ार के पास की इमारत गिर गई है और दो लोग फँसे हैं।",loc:"मेरी लोकेशन जोड़ें",locDone:"लोकेशन जुड़ गई",addr:"गली, इलाका या पहचान की जगह (वैकल्पिक)",send:"मदद भेजें",call:"अगर किसी की जान को ख़तरा है, तो पहले",first:"पर कॉल करें।",mine:"आपकी रिपोर्ट",alert:"आपके इलाके के लिए चेतावनी",alertBody:"आज रात आपके ज़िले में भारी बारिश और बाढ़ की आशंका है। क़ीमती सामान ऊपर रखें और निचली सड़कों से दूर रहें।",src:"नमूना चेतावनी। ज़िला नियंत्रण कक्ष की ओर से, सुबह 9:05।",helplines:"आपातकालीन नंबर",safety:"बाढ़ के समय क्या करें",tips:["जल्दी ऊँची जगह पर चले जाएँ","बिजली का मुख्य स्विच बंद कर दें","बाढ़ के पानी में पैदल या गाड़ी से न जाएँ"]},
pa:{title:"ਦੱਸੋ ਕੀ ਹੋ ਰਿਹਾ ਹੈ",sub:"ਤੁਸੀਂ ਕਿੱਥੇ ਹੋ ਅਤੇ ਤੁਹਾਨੂੰ ਕਿਹੜੀ ਮਦਦ ਚਾਹੀਦੀ ਹੈ, ਇਹ ਲਿਖੋ। ਬਚਾਅ ਕੋਆਰਡੀਨੇਟਰ ਇਸਨੂੰ ਤੁਰੰਤ ਵੇਖਦਾ ਹੈ।",ph:"ਜਿਵੇਂ: ਬਾਜ਼ਾਰ ਕੋਲ ਇਮਾਰਤ ਡਿੱਗ ਗਈ ਹੈ ਅਤੇ ਦੋ ਲੋਕ ਫਸੇ ਹੋਏ ਹਨ।",loc:"ਮੇਰੀ ਲੋਕੇਸ਼ਨ ਜੋੜੋ",locDone:"ਲੋਕੇਸ਼ਨ ਜੁੜ ਗਈ",addr:"ਗਲੀ, ਇਲਾਕਾ ਜਾਂ ਨਿਸ਼ਾਨੀ (ਵਿਕਲਪਿਕ)",send:"ਮਦਦ ਭੇਜੋ",call:"ਜੇ ਕਿਸੇ ਦੀ ਜਾਨ ਨੂੰ ਖ਼ਤਰਾ ਹੈ, ਤਾਂ ਪਹਿਲਾਂ",first:"'ਤੇ ਕਾਲ ਕਰੋ।",mine:"ਤੁਹਾਡੀਆਂ ਰਿਪੋਰਟਾਂ",alert:"ਤੁਹਾਡੇ ਇਲਾਕੇ ਲਈ ਚੇਤਾਵਨੀ",alertBody:"ਅੱਜ ਰਾਤ ਤੁਹਾਡੇ ਜ਼ਿਲ੍ਹੇ ਵਿੱਚ ਭਾਰੀ ਮੀਂਹ ਅਤੇ ਹੜ੍ਹ ਦਾ ਖ਼ਦਸ਼ਾ ਹੈ। ਕੀਮਤੀ ਸਮਾਨ ਉੱਪਰ ਰੱਖੋ ਅਤੇ ਨੀਵੀਆਂ ਸੜਕਾਂ ਤੋਂ ਦੂਰ ਰਹੋ।",src:"ਨਮੂਨਾ ਚੇਤਾਵਨੀ। ਜ਼ਿਲ੍ਹਾ ਕੰਟਰੋਲ ਰੂਮ ਵੱਲੋਂ, ਸਵੇਰੇ 9:05।",helplines:"ਐਮਰਜੈਂਸੀ ਨੰਬਰ",safety:"ਹੜ੍ਹ ਵੇਲੇ ਕੀ ਕਰੀਏ",tips:["ਜਲਦੀ ਉੱਚੀ ਥਾਂ 'ਤੇ ਚਲੇ ਜਾਓ","ਬਿਜਲੀ ਦਾ ਮੁੱਖ ਸਵਿੱਚ ਬੰਦ ਕਰ ਦਿਓ","ਹੜ੍ਹ ਦੇ ਪਾਣੀ ਵਿੱਚ ਪੈਦਲ ਜਾਂ ਗੱਡੀ ਨਾਲ ਨਾ ਜਾਓ"]}};

Object.assign(T.en,{skip:"Skip to main content",tick:"Latest alerts",lvl:"Orange alert: be prepared",n_home:"Home",n_alerts:"Alerts",n_report:"Report an Incident",n_mine:"My Reports",n_tips:"Safety Tips",n_help:"Helplines"});
Object.assign(T.hi,{skip:"मुख्य सामग्री पर जाएँ",tick:"ताज़ा चेतावनी",lvl:"ऑरेंज अलर्ट: तैयार रहें",n_home:"होम",n_alerts:"चेतावनियाँ",n_report:"घटना की रिपोर्ट करें",n_mine:"मेरी रिपोर्ट",n_tips:"सुरक्षा सुझाव",n_help:"हेल्पलाइन"});
Object.assign(T.pa,{skip:"ਮੁੱਖ ਸਮੱਗਰੀ 'ਤੇ ਜਾਓ",tick:"ਤਾਜ਼ਾ ਚੇਤਾਵਨੀਆਂ",lvl:"ਔਰੇਂਜ ਅਲਰਟ: ਤਿਆਰ ਰਹੋ",n_home:"ਮੁੱਖ ਪੰਨਾ",n_alerts:"ਚੇਤਾਵਨੀਆਂ",n_report:"ਘਟਨਾ ਦੀ ਰਿਪੋਰਟ ਕਰੋ",n_mine:"ਮੇਰੀਆਂ ਰਿਪੋਰਟਾਂ",n_tips:"ਸੁਰੱਖਿਆ ਸੁਝਾਅ",n_help:"ਹੈਲਪਲਾਈਨ"});
